# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2

sphinx:
   configuration: docs/conf.py

# Equivalent to: pip install .[doc]
python:
  version: 3
  system_packages: true
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
    - method: setuptools
      path: package
